spring:
  application:
    name: argo
  datasource:
    url: jdbc:postgresql://localhost:5432/argo
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    locations: db/migration
